# Introduction to NumPy
NumPy is the de facto standard for numerical calculations in Python. It can efficiently perform calculations with large data series, matrices, vectors, etc.

### Import NumPy

In [11]:
import numpy as np

#### Create numpy arrays

In [34]:
# create array from list
a_list = [1, 2, 3, 4, 5]
a = np.array(a_list)
print(f'{a = }')

# create empty array
e = np.zeros(10)
print(f'{e = }')

# create range of values (with start value and step size, similar to range)
r = np.arange(10, 15.5, .5)
print(f'{r = }')

# create evenly spaced values between min and max value
x = np.linspace(100, 200, 11)
print(f'{x = }')

a = array([1, 2, 3, 4, 5])
e = array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
r = array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ])
x = array([100., 110., 120., 130., 140., 150., 160., 170., 180., 190., 200.])


#### Slicing arrays

In [38]:
a[2] # access element with index 2 (first element has index 0)

np.int64(3)

In [39]:
a[-2] # access second to last element

np.int64(4)

In [44]:
a[1:4] # subarray from index 1 to index 3 (upper boundary excluded)

array([2, 3, 4])

#### Calculate with arrays

In [29]:
a**2 # operations are calculated element wise

array([ 1,  4,  9, 16, 25])

In [31]:
np.sqrt(x) # numpy provides many mathematical functions

array([10.        , 10.48808848, 10.95445115, 11.40175425, 11.83215957,
       12.24744871, 12.64911064, 13.03840481, 13.41640786, 13.78404875,
       14.14213562])

In [37]:
r * x # calculations with arrays of same length

array([1000., 1155., 1320., 1495., 1680., 1875., 2080., 2295., 2520.,
       2755., 3000.])

### Example: Temperature data
Perform some simple calculations based on temperature data.

In [78]:
path = 'data/zrh_temp_2024.csv' # file containing daily average temperatures for 2024
temperature = np.genfromtxt(path, skip_header=1) # create array from textfile, skip header

In [90]:
n = len(temperature) # number of entries
t_min = np.min(temperature)
t_max = np.max(temperature)
t_mean = np.mean(temperature)
t_std = np.std(temperature)

print(f'number of data points: {n}')
print(f'minimum temperature: {t_min}°C')
print(f'maximum temperature: {t_max}°C')
print(f'yearly mean temperature: {t_mean:.2f}°C')
print(f'standard deviation: {t_std:.2f}°C')

number of data points: 366
minimum temperature: -5.2°C
maximum temperature: 24.9°C
yearly mean temperature: 11.04°C
standard deviation: 7.05°C
