# Introduction to NumPy
NumPy is the de facto standard for numerical calculations in Python. It can efficiently perform calculations with large data series, matrices, vectors, etc.

#### Import NumPy

In [2]:
import numpy as np

### Working with NumPy Arrays

#### Create numpy arrays

In [34]:
# create array from list
a_list = [1, 2, 3, 4, 5]
a = np.array(a_list)
print(f'{a = }')

# create empty array
e = np.zeros(10)
print(f'{e = }')

# create range of values (with start value and step size, similar to range)
r = np.arange(10, 15.5, .5)
print(f'{r = }')

# create evenly spaced values between min and max value
x = np.linspace(100, 200, 11)
print(f'{x = }')

a = array([1, 2, 3, 4, 5])
e = array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
r = array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ])
x = array([100., 110., 120., 130., 140., 150., 160., 170., 180., 190., 200.])


#### Slicing arrays

In [38]:
a[2] # access element with index 2 (first element has index 0)

np.int64(3)

In [39]:
a[-2] # access second to last element

np.int64(4)

In [44]:
a[1:4] # subarray from index 1 to index 3 (upper boundary excluded)

array([2, 3, 4])

#### Calculate with arrays

In [29]:
a**2 # operations are calculated element wise

array([ 1,  4,  9, 16, 25])

In [31]:
np.sqrt(x) # numpy provides many mathematical functions

array([10.        , 10.48808848, 10.95445115, 11.40175425, 11.83215957,
       12.24744871, 12.64911064, 13.03840481, 13.41640786, 13.78404875,
       14.14213562])

In [37]:
r * x # calculations with arrays of same length

array([1000., 1155., 1320., 1495., 1680., 1875., 2080., 2295., 2520.,
       2755., 3000.])

#### Example: Temperature data
Perform some simple calculations based on temperature data.

In [78]:
path = 'data/zrh_temp_2024.csv' # file containing daily average temperatures for 2024
temperature = np.genfromtxt(path, skip_header=1) # create array from textfile, skip header

In [90]:
n = len(temperature) # number of entries
t_min = np.min(temperature)
t_max = np.max(temperature)
t_mean = np.mean(temperature)
t_std = np.std(temperature)

print(f'number of data points: {n}')
print(f'minimum temperature: {t_min}°C')
print(f'maximum temperature: {t_max}°C')
print(f'yearly mean temperature: {t_mean:.2f}°C')
print(f'standard deviation: {t_std:.2f}°C')

number of data points: 366
minimum temperature: -5.2°C
maximum temperature: 24.9°C
yearly mean temperature: 11.04°C
standard deviation: 7.05°C


### Vectors and Matrices

Vectors can be implemented as arrays with 2 (2D vectors) or 3 (3D vectors) elements. Typical vector operations can easily be calculated.

In [14]:
u = np.array([1, 3, 2]) # vector u
v = np.array([3, 2, 4]) # vector v

print(f'sum: u + v = {u+v}')
print(f'difference: u - v = {u-v}')
print(f'scalar multiplication: 3 u = {3*u}')
print(f'dot product: u · v = {np.dot(u, v)}')
print(f'cross product: u x v = {np.cross(u, v)}')

sum: u + v = [4 5 6]
difference: u - v = [-2  1 -2]
scalar multiplication: 3 u = [3 9 6]
dot product: u · v = 17
cross product: u x v = [ 8  2 -7]


A matrix can be represented by a two-dimensional array (i.e. a nested array).

In [56]:
A = np.array([[0, 1, 9], [2, 0, 3], [6, 2, 3]])
B = np.array([[0, 1, 3], [1, 0, 1], [3, 2, 1]])
print(A)
print()
print(B)

[[0 1 9]
 [2 0 3]
 [6 2 3]]

[[0 1 3]
 [1 0 1]
 [3 2 1]]


The symbol @ is used for matrix multiplication:

In [57]:
print(A @ B) # product of A and B
print()
print(A @ u) # A applied to vector u

[[28 18 10]
 [ 9  8  9]
 [11 12 23]]

[21  8 18]


The sub-library numpy.linalg contains additional methods to work with matrices.

In [69]:
from numpy.linalg import inv, eig

#### Inverted matrix

In [70]:
print(inv(A)) # inverse of matrix A
print()
print(A @ inv(A)) # should be identity matrix; deviations are due to numerical errors
print()
print(np.round(A @ inv(A), decimals=5))

[[-0.125       0.3125      0.0625    ]
 [ 0.25       -1.125       0.375     ]
 [ 0.08333333  0.125      -0.04166667]]

[[ 1.00000000e+00  0.00000000e+00  2.08166817e-17]
 [-1.38777878e-17  1.00000000e+00  6.93889390e-18]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


#### Eigenvalues and eigenvectors

In [74]:
values, matrix = eig(A)

print(values) # eigenvalues of A
print()
print(matrix) # eigenvectors of A as a matrix, columns are eigenvectors

[ 9.81507291 -6.         -0.81507291]

[[-6.54194593e-01 -8.32050294e-01  2.67585631e-01]
 [-3.39827915e-01 -6.83846344e-18 -9.60001397e-01]
 [-6.75682190e-01  5.54700196e-01  8.24332888e-02]]


In [89]:
vectors = matrix.T # eigenvectors correspond to rows of transposed matrix

for i in range(0, 3):
    print(np.round(A @ vectors[i] - values[i] * vectors[i], decimals=5)) # verify if A v = \lambda v

[-0. -0. -0.]
[ 0. -0. -0.]
[ 0. -0.  0.]


#### Example: Solve system of linear equations
Solve the following system of linear equations:

$x + 2y + 3z = 13$ \
$y - z = -2$ \
$2x - y + z = 6$

The system can be written as

$M \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \vec{b}$

with $M = \begin{pmatrix} 1 & 2 & 3 \\ 0 & 1 & -1 \\ 2 & -1 & 1 \end{pmatrix} \quad$ and $\quad \vec{b} = \begin{pmatrix} 13 \\ -2 \\ 6 \end{pmatrix}$

The solution is then $\begin{pmatrix} x \\ y \\ z \end{pmatrix} = M^{-1}\, \vec{b}$

In [99]:
M = np.array([[1, 2, 3], [0, 1, -1], [2, -1, 1]])
b = np.array([13, -2, 6])

x, y, z = inv(M) @ b

print(f'The solution is {x=:.1f}, {y=:.1f}, {z=:.1f}')

The solution is x=2.0, y=1.0, z=3.0
